### Create
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Produto A",
  "quantity": 10,
  "price": 99.99
}

### List
GET http://localhost:3000/products

### Update
PUT http://localhost:3000/products/1
Content-Type: application/json

{
  "quantidade": 20
}

### Delete
DELETE http://localhost:3000/products/1
